apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  refreshInterval: ${interval}
  secretStoreRef:
    name: google-secret-store
    kind: SecretStore
  target:
    name: ${name}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ${gsm_path}
      version: latest
  # data:
  # - secretKey: ${name}
  #   remoteRef:
  #     key: ${gsm_path}      # name of the GCPSM secret key
  #     version: latest