apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: google-secret-store
  namespace: ${namespace}
spec:
  provider:
    gcpsm:
      projectID: ${project_id}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-k8s-secret
            key: gcpsm-k8s-secret.json
          # secretName: gcpsm-k8s-secret
          # secretKey: key.json
          # namespace: ${namespace}
