apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: re100-dev-eps-api-backend-config
  namespace: re100-dev
spec:
  healthCheck:
    checkIntervalSec: 15
    healthyThreshold: 1
    port: 8000
    requestPath: /re100health
    timeoutSec: 5
    type: HTTP
    unhealthyThreshold: 2
